/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mytank_MyTank */

#ifndef _Included_mytank_MyTank
#define _Included_mytank_MyTank
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     mytank_MyTank
	* Method:    doSomething
	* Signature: (II[[B)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_mytank_MyTank_doSomething
	(JNIEnv *, jobject, jint, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
